version: '2'

services:
    proxy:
        image: nginx
        container_name: proxy
        depends_on:
            - front
            - back
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 5011:3000

    front:
        build:
            context: services/client
        container_name: front
        ports:
            - 8080

    db:
        image: postgres
        container_name: db
        ports:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=foobar
            - POSTGRES_DB=postgres
        expose:
            - 5432
        volumes:
            - ./services/db/init.sh:/docker-entrypoint-initdb.d/init.sh

    back:
        build:
            context: services/server
        container_name: back
        depends_on:
            - db
        ports:
            - 8081

